### ISSUE TITLE
Authenticators Status API returns status of a specific authenticator

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1062]
### Personas

|     **Persona**    |                       **Description**                             |
|:---------------:|:-----------------------------------------------------------------:|
| Conjur Operator | A Conjur user with enhanced privileges (loads policies to root, configures authenticators, etc.) |
| Conjur User     | A developer/app that needs to login to Conjur to retrieve secrets |

# Introduction 

## Feature Overview

**As a** Conjur operator
**I'd like to** know that an authenticator is configured correctly
**So that** I can complete the configuration properly if it's incomplete (or remove
it if it's not needed).

This feature lets the person who configures an authenticator to get an immediate feedback 
on the configuration, before any user needs to run an authentication request.

For example, the OIDC Authenticator configuration includes whitelisting the authenticator in the CONJUR_AUTHENTICATORS variable:

`CONJUR_AUTHENTICATORS=authn-oidc/adfs,authn`

Let's say the Conjur Operator configured the OIDC Authenticator and forgot to whitelist 
the authenticator in the CONJUR_AUTHENTICATORS variable. Without the Authenticator Status API, 
the first time the user will encounter the error will be in an authentication request. 
A user `alice` will try to authenticate with OIDC and will get a 401 Unauthorized 
response without any description on what happened (the answer will be in the logs which 
are probably inaccessible to her) even if the actual request is ok. The main problem 
here is that the Unauthorized response has nothing to do with the actual request, as 
the problem is not in it. The problem is in the configuration which was made by another 
person in another time. With the Authenticator Status API the person who does the configuration will 
get an immediate feedback on it, and the users that are *using* the authenticators will not 
be unauthorized due to configuration errors.

### Current Mechanism

The current mechanism for understanding that there is a problem in the Authenticator configuration is as follows:

1. The Operator configures the Authenticator according to the docs
1. A user tries to authenticate
    1. this may be the Operator himself imitating a user to verify the authenticator works in the dev env
1. The user gets a 401 Unauthorized response
    1. There are other response codes possible but configuration issues will be 401
1. The user reports to the operator that there is an issue
    1. This one is tricky as the user might not know who to report this to.
    1. Again, this may be the operator himself
1. The operator looks in the logs (according to the docs) and finds the issue
1. The operator fixes the issue

This can be iterative as there might be several issues. It is possible to assume that in the case 
above, the operator will solve this with the user and will ask him to try to authenticate again and 
if it's still Unauthorized will solve the configuration issues one-by-one. 

### Process Logic

In the following example, a Conjur Operator configured the authenticator `authn-1/service-id` and would like
to know if the configuration was successful. 

1. The Conjur operator logs into Conjur
1. The Conjur operator configures the Authenticator `authn-1/service-id` according to the docs
1. The operator runs the Authenticator Status request: `GET /authenticators/authn-1/service-id/<account>/status`
1. The operator gets a response:
    1. In case the authenticator is healthy, a response with code 200 and the following body:
        
        ```
        {
           "status": "ok"
        }
        ```
    1. In case the authenticators isn't healthy, a response with code 500 (more info [here](authenticator_status_api.md#response-code-for-unhealthy-authenticators)) and the reason in the body. For example, in case the requested authenticator is not implemented in Conjur the body will be:
        ```
        {
          "status": "error",
            "error": "#<Errors::Authentication::AuthenticatorNotFound: CONJ00001E Authenticator 'authn-not-exist' is not implemented in Conjur>"
        }
        ```
        
    1. In case there is more than one error in the authenticator, only the first one found will be showed.
1. The operator understands the issue from the response and fixes the issue
1. The operator runs the request once again and until he gets a healthy response

#### Special Cases
1. The authenticator does not exist in Conjur -  return a 404 response.
    1. `GET /authenticators/authn-not-exists/<account>/status` -> 404
1. The authenticator exists but we didn't implement the status-check - return a 503 response.
    1. `GET /authenticators/authn-ldap/<account>/status` -> 503 Not Implemented

#### Security

This endpoint reveals some serious details on the Conjur environment, so it should be 
secure. Any request lacking a valid access token will be responded with a 403 code.

As the use-case of this endpoint is to be hit by the operator who configures an
authenticator, we will limit access to this endpoint by defining a webservice on it,
and granting permission on it.

We will add a new section to the original authenticator policy:
```
- !policy
  id: conjur/authn-oidc/<service-id>
  body:
  - !webservice
    annotations:
      description: Authentication service for <service-id>, based on OpenID Connect.

  - !variable
    id: provider-uri
 
  - !variable
    id: id-token-user-property
 
  - !group
    id: users
    annotations:
      description: Group of users who can authenticate using the authn-oidc/<service-id> authenticator

  - !permit
    role: !group users
    privilege: [ read, authenticate ]
    resource: !webservice

 ### This part is new:

  - !webservice
    id: status

 - !group
    id: managers
    annotations:
      description: Group of users who can check the status of the authn-oidc/keycloak authenticator

  - !permit
    role: !group managers
    privilege: [ read ]
    resource: !webservice status
```

We added a `status` webservice, a `managers` group and permitted that group to `read` the webservice.

Just like with the `users` group, the operator now needs to load a policy that adds users to the `managers` group, as follows:
```
- !grant
  role: !group conjur/authn-oidc/<service-id>/managers
  member: !group <user-group>
```

This way every user that is in `<user-group>` will have access to the status endpoint and any user who is not in that group will have no access

#### Audit 

As described in the security section, this endpoint will be closed to specific Conjur users. As for that,
we need to audit any successful/unsuccessful access to this endpoint. 

### DoD

- [x] Documentation was added
- [x] Documentation was reviewed by PO
- [x] Test plan written and reviewed by PO & QAA
- [x] Automatic integration tests written according to the test plan and passed successfully
- [x] UT written for all classes\functions\major logic flows and passed successfully
- [x] Security review was done
- [x] Security action items were taken
- [x] Logs were added to enhance supportability
- [x] Logs were reviewed by PO & TW

# Appendix
### Response code for unhealthy authenticators

In case of an error we need to return a response code which will best indicate the issue. Let's explore the possibilities and find the best 
response code. 

2xx isn't good as it doesn't indicate there is an error and 3xx is irrelevant as there is no redirection.
A valid option will be to return an error response code (4xx, 5xx). In this case the 500's make more sense as the error here is not in the 
actual request so it's more of a server error that a client error. The possibilities for 5xx responses are:

- 500 Internal Server Error
    - Con: This is very general and we should try to avoid it when possible
- 501 Not Implemented
    - Con: Well, this is actually implemented. 
- 503 Service Unavailable
    - Con: This doesn't really tell the story as the service that we're calling - The Authenticator status service - is actually available. 
- 502 Bad Gateway & 504 Gateway Timeout
    - Irrelevant as this is not a gateway.

Although we'd like not to return 500 when possible i think there is no specific error code which tells the story here so we need to go with the 
general 500 Internal Server Error

Conclusion: return 500 Internal Server Error.

**Comment by alexkalish** [comment]
This looks like a *huge* usability improvement! Great work.

I realize that the implementation is (nearly?) complete (I totally should have read it earlier, sorry), but I had a few comments after reading this.  Feel free to ignore them or just consider them in the future if the :ship: has already sailed.
1. I noticed that the `error`in the status response was the result of calling `#to_string` on a Ruby object (or the like).  In general, I think it's best practice to avoid returning programatic errors directly to the user without first transforming them for human consumption.  Also, there isn't any reason to expose users to our error class names or language choice.
2. I'm not sure that using the 500 status to indicate that the authenticator isn't properly configured is necessarily ideal.  I think it conflates the status of the authenticator with the status of the HTTP request.  If I hit this API and get back 500, without looking at the body, I won't know if this means the whole API is down or if that status is negative.  I would expect a 200 to mean that I successfully fetched the status and would need to examine the body to see what it is.  Did you look around to see what other companies or products do in similar situations?
3. This is a bit more architectural.  Do we have a standard for formatting JSON responses from APIs?  For example, do we usually omit empty keys (aka `error` for `ok` status) or include them with an empty value?  The responses here look totally reasonable.  I'm just curious how they compare to the rest of the product.

Thanks so much!

**Comment by orenbm** [comment]
Thanks for input @alexkalish !

The ship has indeed sailed :)

to answer your comments:

1. You would prefer that we return only the error message? something like this:
```
{
  "status": "error",
    "error": "CONJ00001E Authenticator 'authn-not-exist' is not implemented in Conjur"
}
```
 @InbalZilberman any thoughts on that?
2. I actually thought about this a lot. I documented my thoughts in the Appendix of the epic (https://github.com/cyberark/conjur/issues/1062). You can see them under "Response code for unhealthy authenticators". Let me know what you think.
3. on top of my head, we do the same for policy loading. not sure how much thought was invested into that.

**Comment by alexkalish** [comment]
No worries about the 🚢 sailing.  I realize that I'm late to the game. 😸 

1. Yes, exactly.  As I said, error messages sent back to customers should be plaintext and curated.  And we shouldn't be passing completely unexpected error messages back as well.  At best, it could lead to a confusing UX.  At worst, I would normally say it's a security issue (as it exposes unwanted information about our implementation), but since this is Ruby and the customer obvious has access to the app, it's a moot point.  If @InbalZilberman agrees, maybe a small story could be filed to correct this?
2. I did read through your appendix and your logic is definitely sound as written.  Returning a 500 is a totally reasonable choice.  But I think it's worth considering if the code is representing the status of the HTTP call vs. the resource being fetched.  For example, some customers might have HTTP clients that will do an automatic retry (or some other behavior) on 500 with the presumption that the call itself failed, as opposed to the resource having an error state.  Mostly, I think it would be great if we had a best practices policy on this type of subject for the future.
3. Great!  Similar to above, I think there would be valuable in having some best practices around structuring REST API JSON responses.

@rafis3 or @jvanderhoof: Any thoughts on items two or three above?

Thank you, @orenbm!

**Comment by InbalZilberman** [comment]
Regarding 1. Yes I agree with @alexkalish . good catch! I was sure that this is the case. this was the examples I saw so far.
Regarding 2 I think that mostly humans will use the status api represented here so I am not sure this is the case.
Regarding 3 I totally agree with you regarding REST API conventions. we actually have instructions for this in CyberArk. https://ca-il-confluence.il.cyber-ark.com/display/GRnD/REST+API+Standards+in+CyberArk#/
