### ISSUE TITLE
Hosts can authenticate with authn-k8s with their machine identity in annotations

### ISSUE THREAD

**Issue by orenbm** [cyberark/conjur#1244]
At this point, hosts have their machine identity in their ID (e.g `test-namespace/service-account/test-sa`). We would like to let users configure hosts with the machine identity stored as annotations. This will:
1. Improve UX as users can give their hosts a name that identifies their purpose.
2. Let users constraint their hosts with more than 1 machine identity property. Currently you can have a constraint on one property (service account, deployment, pod name, etc.) whereas with annotations we can have more than one.

A host will be defined as follows:
```
- !host
  id: test-app
  annotations:
    kubernetes/namespace: test-namespace
    kubernetes/service_account: test-sa
    kubernetes/deployment: test-deployment
    kubernetes/authentication-container-name: test-container
```

Note that in the example above, we have a constraint on both the service account and the deployment. This is not available at this moment where the machine identity is in the host id.

DoD
- [x] Solution designed is approved by team
- [x] Hosts can authenticate with authn-k8s with their machine identity in annotations
- [x] Hosts can authenticate with authn-k8s with their machine identity in the ID
- [x] Backwards compatibility is held
  - [x] new client with an old server
  - [x] old client with a new server
- [x] Test plan is reviewed by PO and QA
- [x] Tests are implemented according to the test plan
- [x] Logs were added according to the design
- [x] Github tickets are created for documentation with instructions
- [x] Versions are bumped in all relevant projects
  - [x] conjur
    - [x] appliance
  - [x] conjur-authn-k8s-client
    - [x] secrets-provider-for-k8s
    - [x] secretless-broker

**Comment by rafis3** [comment]
@orenbm, @InbalZilberman do you mind if we change the `kubernetes/` prefix to the authenticator prefix? So it would looks something like that:

```
- !host
  id: test-app
  annotations:
    authn-k8s/namespace: test-namespace
    authn-k8s/service_account: test-sa
    authn-k8s/deployment: test-deployment
    authn-k8s/authentication-container-name: test-container
```

I think it's important to keep the same terminology so our users would easily understand which authentication it belongs to. This same name is also used by the app when calling the API endpoint of that authentication.

**Comment by orenbm** [comment]
2 comments:
1. Do we also need the service-id? @InbalZilberman is checking this/
2. currently we have the annotation `kubernetes/authentication-container-name`. I guess we can search for both and leave the current one working for backwards compatibility.
