### ISSUE TITLE
OpenAPI-Driven Conjur SDK

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#1886]
# OpenAPI-Driven Conjur SDK

Details TBA

## Stories

- [x] (Spike) Review current [Draft OpenAPI Implementation](https://github.com/conjurinc/draft-conjur-openapi-spec) to determine what endpoints are missing, if any
- [ ] Draft OpenAPI Implementation is publicly available under a Community Certification Level
- [ ] (Spike) There is a plan for auto-generating an initial set of client libraries based on the Draft OpenAPI Implementation

**Comment by izgeri** [comment]
Duplicate of cyberark/conjur-openapi-spec#13
