### ISSUE TITLE
CLI Research

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#1892]
**Feature Overview & Customer Need**
As part of our Dockerless project we need to support Conjur CLI to be on deployed on VMs or local computers of our users.
The platforms the CLI need to support are:

- RHEL 7 , 8
- Windows 10
- Mac (like ours)

We need to investigate the steps and effort it takes to provide Conjur CLI in each platform, think about security aspects and so on.
The core functionality should be supported in each platform: init, login, authenticate, load policy and fetch secrets. 
The deployment should be 
1. Manual and automatic 
2. Only one or two steps at most.
3. Recommended - be the same for each platform

Please compare the 2 CLI  we have today in [Ruby](https://github.com/cyberark/conjur-cli) and [Go](https://github.com/cyberark/conjur-cli-go) and Python one :) in the following aspects:
- What it takes to deploy the CLI on the given platforms
- What functionality each CLI provides today
- Quality level - what is the quality level of each CLI 
- Other aspects like security/ configurations  if there are any differences 
- Deployment UX
Work closely to PO to understand and define together the deployment UX and the functionality differences . 

**DOD**
- [x] Research page with all info support Conjur CLI to be on deployed on VMs or local computers
- [x] Understand the alternatives
- [x] Security review was done and issues were raised
- [x] Research results presented and shared
- [x] High level effort estimations and risks
