### ISSUE TITLE
Clients are updated to manage API key rotation appropriately after v1.9.0

### ISSUE THREAD

**Issue by izgeri** [cyberark/conjur#1900]
Following the release of v1.9.0 which included a [medium security bug fix](https://github.com/cyberark/conjur/security/advisories/GHSA-qhjf-g9gm-64jq), we have some clients capable of rotating API keys which need to be updated to ensure they follow the new guidelines.

In Conjur v1.9.0+ (and DAP 11.7+), when a role is rotating its own API key, it must authenticate to the `/api_key` route using basic authentication, and _cannot_ send the request with only an access token.

That is, the request should look something like:
```
curl -f -X PUT -s --user "host/{host ID}:{api_key}" http://{Conjur URL}/authn/{accouont}/api_key
```

In this mini-epic, we track the work required to make these downstream updates.

- [ ] Ruby client uses basic authentication for API key rotation events - cyberark/conjur-api-ruby#181
- [ ] There is a new release of the Ruby client including a fix for API key rotation - cyberark/conjur-api-ruby#182
- [ ] Update CLI to consume new Ruby client version - cyberark/conjur-cli#297
- [ ] There is a new release of the Conjur CLI - cyberark/conjur-cli#298
