### ISSUE TITLE
Build DAP apps RPMs in GA level

### ISSUE THREAD

**Issue by nessiLahav** [cyberark/conjur#1973]
Our Dockerless DAP installation contains 3 dap apps RPMs: possum, evoke and ui
Those RPMs are not in production level, there are some issues i found about the possum RPMS which are relevant to all 3:

## For stage 1:
• There are no dependencies for possum RPM (nginx, postgresql, syslog …)
• Duplicate packages issue, I am not sure how to reproduced it but at some point I got to this state in the system where I have duplicate conjur -possum installed:
```
rpm -e conjur-possum
error: "conjur-possum" specifies multiple packages:
 conjur-possum-1.11.1.8_ba0a7bdd-1.x86_64
  conjur-possum-1.11.1.8_ba0a7bdd-1.x86_64
```

## For post stage 1:
• RPM is not signed (not for stage 1)
```
rpm -qi conjur-possum-1.11.1.8_ba0a7bdd-1.x86_64 | grep Signature
Signature   : (none)
```
• RPM contains redundant files (for example: /opt/conjur/possum/.github/ISSUE_TEMPLATE/bug.md, /usr/lib/.build-id/b0/5499ee3a78a1250e23f955d917a78b553d635f)
`rpm -ql conjur-possum-1.11.1.8_ba0a7bdd-1.x86_64`
• Uninstall command do not delete files
•  UX - a lot of duplicated errors when installing the RPM without creating conjur user:
```
	warning: group conjur does not exist - using root
	warning: user conjur does not exist - using root
```
	
• The above error can create the following RPM error on installation: which can be solved by simply delete the file
```
rpm -i conjur-possum-1.11.1.8_ba0a7bdd-1.x86_64.rpm	
warning: waiting for transaction lock on /var/lib/rpm/.rpm.lock 
```

DoD:

- [ ] Challenge this GAP against PM the QA Architect if it wort the effort, because most of the errors can be handled in ansible and not be exposed to the customer 

- [ ] Investigate if there are more GAPs in our RPMS to be GA level ( the above list is just an example)

- [ ] Fix the RPMs build to create GA level DAP apps RPMS ( this fix will affect the appliance)

**Comment by izgeri** [comment]
@nessiLahav can this issue be focused on the work that you plan to do in the Conjur OSS repo? it looks like you may want to create a separate "GA quality RPMs" in your enterprise project, and focus this issue on the work to be done on the Conjur RPM to meet your end goals.

**Comment by nessiLahav** [comment]
After consulting with Rafi we have reached the conclusion that the value here is small in comparison to effort, so we decided to close to epic
