### ISSUE TITLE
A CI environment exists for verifying PKI capabilities 

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#682]
I, as a Conjur Developer, want the CI pipeline to verify PKI features (e.g. certificate signing), so that I can verify behavior quickly during development.

#### Tasks
- [x] Create Root CA during CI
- [x] Create Intermediate CA during CI
- [x] Generate server certificate and verify cert chain using OpenSSL CLI (temporary until Conjur CA exists)

**Comment by micahlee** [comment]
This story is no longer necessary. CI environment is included in https://github.com/cyberark/conjur/issues/684
