### ISSUE TITLE
Kubernetes Authenticator Has No Technical Debt

### ISSUE THREAD

**Issue by jvanderhoof** [cyberark/conjur#708]
Work to cover refactor of Authn-Kubernetes.

ETA for completion of this epic: 2018-09-14
Confidence level of ETA accuracy: Medium

## Stories
- [x] Kubernetes authenticator cukes pass (parent of #713)
- [x] K8s authenticator.rb has clean code (parent of #715)
- [x] K8s authenticator only creates one CA per service (parent of #716)
- [x] K8s authenticator has clean ValidatePodRequest class (parent of #719)
- [x] K8s authenticator has clean InjectClientCert class (parent of #720)
- [x] Refactor kubectl exec class (parent of #729)

## Future Stories
- Kubernetes authenticator cukes have been refactored (#714)

## Won't Do
- kubectl_exec.rb has unit tests (#718)

**Comment by brikelly** [comment]
@jtuttle @jonahx please add a doc story to this epic

**Comment by jtuttle** [comment]
@brikelly Sorry I missed this comment before. I don't think we actually need any doc updates for this epic. It's all just reorganizing existing code and it's all internal to the k8s authenticator. The API endpoints that are exposed to the public aren't changing at all as a result of these changes.
