### ISSUE TITLE
Special characters in resource name causes audit log error

### ISSUE THREAD

**Issue by micahlee** [cyberark/conjur#754]
Estimated ETA: 11/29 (60% confident)

As a Conjur operator, I don't want non-alphanumeric characters to cause problems.

GIVEN a resource with the ID of `{ []: {[]:[]} }`
WHEN I load it into Conjur through a policy
THEN the resource ID audits display correctly in the audit log

**Dev Notes**
Example resource ID:
```
 { []: {[]:[]} }
```

Resulting error in log:
```
{
  "PROGRAM": "syslog-ng",
  "PID": "27",
  "MESSAGE": "Error processing log message: <37>1 2018-10-05T05:16:32.603Z - conjur 7aa3b79d-0447-472f-8179-6dc425de694c policy [auth@43868 user=\"ConjurDev:user:admin\"][subject@43868 role=\"ConjurDev:user:{ []: {[]:[]} }@users\"][action@43868 operation=\"change\"][policy@43868 id=\"ConjurDev:policy:users\" version=\"15\"] ConjurDev:user:admin changed role ConjurDev:user:{ []: {[]:[]} }@users",
  "LEVEL": "err",
  "ISODATE": "2018-10-05T05:16:32.603+00:00",
  "FACILITY": "syslog"
}
```

Reported in slack here: https://conjurhq.slack.com/archives/CCMKTQMH6/p1538717239000100

---

### Task Breakdown
- ~Parent of #802: Audit Setup Instructions are Documented~
- [x] Parent of #803: Conjur Dev environment includes start flag to enable audit
- [x] Parent of #574: Audit Tests are Run in the CI Pipeline
- [x] Parent of #804: Audit tests verify handling of special characters in Resource fields
