### ISSUE TITLE
Supporting ID Token as an authentication method in Conjur

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#838]
Note:
**This feature is developed as a POC**

**Feature Overview & Customer Need**
The customer, would like to following flow to work:

An app user logging on to the app portal or through PSMP, going through a OIDC authentication process implemented by the app connecting to an OIDC provider. The app retrieves an ID token or an OAuth access token of the user in which an ID token exists.

The app connects to other applications\services which are involved in the main application flows and would like to be able to leverage the token acquired from the portal in order to login to Conjur and retrieve secrets.

Conjur should provide an authentication web service that will get as an input the ID token then it will 
•             Validate the ID token 
•             Understand the user’s Conjur identity and based on a predefined policy what permissions the user has
•             Provide the right Conjur access token with which the secret is retrieved and other Conjur actions are made.

In Summary, Conjur will provide an ID Token authenticator is a new authenticator which authenticate users using their ID token against OIDC provider and then returns their Conjur identity.

**Process Diagram**
![image](https://user-images.githubusercontent.com/26732770/51806128-afabb400-227e-11e9-9afe-dcef2d329ca4.png)
**Process Logic \ XDD**
**Configuration in OIDC provider** 

- IT\Infosec  registers the Conjur application with OIDC provider to obtain a client ID, client secret and org. Described here for Okta as an example. 

- IT\Infosec enrolls some of the users to use different factors if at all, described here for Okta as an example. 

**Set up the identity provider authenticator in Conjur** 
 - Conjur admin\Infosec adds the identity provider (Okta) URL to Conjur policy with client ID, client secret, and org as variables. 
Another variable called "IDTokenUserProperty" will be set with the name of the property in the ID Token by which we will map the user name in Conjur
```
-!policy 
 id:conjur/authn-oidc/okta/ 

 body:
 -!webservice 
   annotations: 
     description:Authentication service for Okta, based on Open ID Connect. 
    
    - !variable
      id: provider-uri #Okta uri
	 	
    - !variable
      id: id-token-user-property #value for example: preferred_username
	 
   -!group 
     id: okta-users 
     annotations: 
      description:  
        Roles authorized to use the authn-oidc/okta webservice. Usually has a layer member which contains enrolled applications. 
 
  -!permit 
    resource: !webservice 
    privilege: [ read, authenticate ] 
    role: !group okta-users
```
 
-  In the following example we will assume that a user named alice is part of LDAP users that were assigned also to okta-users. Alternatively, the flow could be applicable also for hosts

 - Enable the authn-oidc authenticator by setting the CONJUR_AUTHENTICATORS environment variable. For example: CONJUR_AUTHENTICATORS=authn-oidc/okta 

**Configure secrets with permissions to some okta users**
A policy with vars /JIRA-frontend/JIRAOracleDB/username & /JIRA-frontend/JIRAOracleDB/password and permissions to alice to read and execute. These vars was deployed by JIRA Conjur admin. The values were added to the vars.
```
`- !policy
  id: JIRA-frontend
  annotations:
    description: the JIRA microservice that is responsible for user interaction
  body:
  - &variables
    - !variable JIRAOracleDB/username
    - !variable JIRAOracleDB/password
  - !permit
    role: !user alice
    privilege: [ read, execute ]
    resource: *variables`
```

**User is identified through an Open ID protocol**

- Alice is connected to App (in our case JIRA) that redirect her to identify herself in an  Open ID protocol.
- The APP gets hold of the ID Token of Alice.
- It uses this ID Token to connect with other parties like other App microservices.

**App connects to Conjur to retrieve secrets**

- App calls authn-oidc/okta/  to login with Alice ID Token in return it get Conjur access token.
- Conjur knows how to map the ID Token to it's user in Conjur and also verify the correctness of the ID Token against the ID provider.
- With this access token is retrieves vars /JIRA-frontend/JIRAOracleDB/username & /JIRA-frontend/JIRAOracleDB/passwordAssumptions

- The app microservice knows how to refresh the OAuth access token and ID token on her own.

**Open Issues:**
How to map Conjur users\hosts to OIDC provider users\hosts?

**Support**
This feature will be developed as a **POC** only

**Research**
**DOD**
- [x] Research page with all info regarding OIDC App 2 App HLD\Research result
- [x] Test plan written and reviewed by PO & QAA
- [x] Security review was done and issues were raised
- [x] Research results presented and shared
- [x] High level effort estimations and risks

**Implementation First Phase- internal mapping mechanism** 
We will start implementation with an internal mapping mechanism that has the following assumptions:
1. The field in the ID token is email.
2. The email will map to a username of a root user in Conjur

**Demo**
1.  Configuration in OIDC provider 
2.  Set up the identity provider authenticator in Conjur 
3.  Enable the authn-oidc authenticator by setting the CONJUR_AUTHENTICATORS environment variable. 
4.  Configure secrets with permissions to some oidc users
5.  Alice is connected to App (in our case JIRA) that redirect her to identify herself in an  Open ID protocol.
6.  The APP gets hold of the ID Token of Alice.
7.  It uses this ID Token to connect with other parties like other App microservices.
8.  App connects to Conjur to retrieve secrets
9.  App calls authn-oidc/okta/  to login with Alice ID Token in return it get Conjur access token.
10.  Conjur knows how to map the ID Token to it's user in Conjur and also verify the correctness of the ID Token against the ID provider.
11.  With this access token is retrieves vars /JIRA-frontend/JIRAOracleDB/username & /JIRA-frontend/JIRAOracleDB/passwordAssumptions 
12. The app microservice knows how to refresh the OAuth access token and ID token on her own.

**DOD**
- [x] Implement an OIDC authn for App 2 App scenario with internal mapping 
- [x] Automatic integration tests written according to a test plan and passed successfully | Done for happy path and several additional flows for the POC
- [x] UT written for all classes\functions\major logic flows and passed successfully
- [x] Security review was done
- [x] Security action items were taken
- [ ] Performance tests were done - no performance regression has been made
- [ ] Supportability tasks were written in OIDC App 2 App supportability page
- [x] Enhance logs and supportability according to guidelines in Supporting+ID+Token+as+an+authentication+method+in+Conjur#SupportingIDTokenasanauthenticationmethodinConjur-Logs&AuditGuidelines
- [ ] Fill in the logs in the feature doc
- [ ] Logs were reviewed by TW and PO
- [ ] Fill in the configurations in the feature doc
- [ ] Configurations were reviewed by PO
- [x] Documentation HO to TW and review docs

# Delivery plan

## Debts from Okta integration
- [x] (Parent of #864) Research - self sign issue (more details: ONYX-1779)
- [x] (Parent of #865) Dev - Base on self sign research decision
- [x] (Parent of #852 ) Dev - Refactoring strategy
- [x] (Parent of #853) Dev - Change previous OKTA APIs and adapt scripts and automations env
- [x] (Parent of #866) Testing - UT Infrastructure rspec

## Infrastructure and others
- [x] (Parent of #846) Plan - Design test app and running environment for ID token authenticator
- [x] (Parent of #855) Plan - summarize Okta integration for future use
- [x] (Parent of #856) Research - Dev environment to test ADFS
- [x] (Parent of #857) Research - ID Token validation ( only check if active=true?, claims?)
- [x] (Parent of #858) Research - Do i have issues with authenticator and Conjur Env (satellite and one master), Design wise and search for open issues in Conjur
- [x] (Parent of #859) Research - Check if LDAP sync working with email as a user name
- [x] (Parent of #860) Dev - Change the start script to create a proper dev env for this feature
- [x] (Parent of #863) Testing - Automation env to run against s ADFS or using key cloak ?

## Implementation
- [x] (Parent of #874) Dev end to end flow with hardcoded email as Conjur user in root policy
- [x] (Parent of #875) Dev - ID Token is validated
- [x] (Parent of #876) Verify Logs and error handling in OIDC flow
- [x] (Parent of #878) Fixes/Surprises form previous Okta feature (Like the error in audit before identifying the User)
- [x] (Parent of #879)  Prepare OIDC code for next iteration
- [x] (Parent of #889) User can modify the id token property to link to Conjur username
 
## Testing
- [x] (Parent of #867) Write test plan
- [x] (Parent of #868) Retrieve ID Token from keycloak in script
- [x] (Parent of #869) Open Source - run manual tests according to test plan
- [x] (Parent of #870) Production env - run tests according to test plan
- [x] (Parent of #872) create automated tests according to test plan

## Docs
- [x] (Parent of #880) Write docs
- [x] (Parent of #151) Create PDF for oidc docs
- [x] (Parent of #146) Add authentication main page to OIDC PDF

**Comment by nessiLahav** [comment]
**User experience flow**

1. OIDC Configuration
- Enable the authn-oidc authenticator by setting the CONJUR_AUTHENTICATORS environment variable. For example: CONJUR_AUTHENTICATORS=authn-authn-oidc/adfs 
- Load a policy which defined the authn-oidc authenticator according to feature doc which contains the Conjur Client ID & Secret in ADFS (oidc provider)
- Create a Conjur user which known to ADFS and has permission to oidc authenticator
- Assumption: The user is defined in the root policy
2. Given i have ID Token
- Application has as ID Token of user that already authenticate through ADFS 
- The ID Token contains the email of the user
3. Authenticate base on ID Token
- App access Conjur authn-oidc authenticate api and sending the id_token
- authn-oidc validate the ID Token 
- Identify the user 
- return Access token to Conjur 

**Design**
[ID Token as an authentication method in Conjur (1).pdf](https://github.com/cyberark/conjur/files/2828986/ID.Token.as.an.authentication.method.in.Conjur.1.pdf)

**Comment by jtuttle** [comment]
A few questions regarding the above posts:

@InbalZilberman 
- Why does Conjur need to be registered w/ Okta? If I'm following the design correctly, the only direct communication between Conjur and Okta is validating the ID token from the application (i.e. Jira), which I think needs to be done using Jira's client ID + secret.
- Has anyone looked into the complexities of performing ID token validation yet or are we black-boxing it for now? With Okta and Google, it looks like you can either validate locally with a set of public keys they provide or remotely against a validation API. Either way, there's provider-specific information that Conjur needs to know to perform validation and we'll need to manage these differences in the authenticator.
- In a similar vein, has anyone figured out if performing the local validation alone is sufficiently secure? It would be great to avoid having to make that additional network call on every request to the authenticator.

@nessiLahav A few questions:
- Why are we assuming the OIDC authenticator user has to be defined in the root policy?

**Comment by InbalZilberman** [comment]
* We have POCed and saw that also Conjur can validate an ID token even if it connect to the OIDC provider with its own client and not the JIRA one. If this is indeed possible that would be great!! if not the values of the client vars would be of JIRA.
* Regarding the validating of the ID Token @nessiLahav has performed some POCs. Can you please elaborate on the differences you saw?
* @nessiLahav \ shahar what do you think of locally validating?

**Comment by nessiLahav** [comment]
# Delivery plan

## Infrastructure and others
- [ ] (Parent of #845) Plan - POC for JPMC, design the test App and the running environment EE 1
- [ ] (Parent of #??) Plan - summarize Okta integration for future use  EE 1
- [ ] (Parent of #??) Research - ID Token validation ( only check if active=true?, claims?)  EE 0.5
- [ ] (Parent of #??) Research - Dev environment to test ADFS  EE 3
- [ ] (Parent of #??) Research - Do i have issues with authenticator and Conjur Env (satellite and one master), Design wise and search for open issues in Conjur EE 1
- [ ] (Parent of #??) Research - Check if LDAP sync working with email as a user name EE 3
- [ ] (Parent of #??) Dev - I have dev env EE 4
- [ ] (Parent of #??) Dev - Change the start script to create a proper dev env for this feature EE 3
- [ ] (Parent of #??) Dev - App for testing EE 5
- [ ] (Parent of #??) Testing - in continue to start script change also the CI script EE 2
- [ ] (Parent of #??) Testing - Automation env to run against s ADFS or using key cloak ? EE 1

## Security 
- [ ] (Parent of #??) Research - how to protect from: Certificate Pinning to avoid MITM
- [ ] (Parent of #??) Research - how to protect from: Amplification/Spoof attack
- [ ] (Parent of #??) Research - how to protect from: DDos
- [ ] (Parent of #??) Design - if admin Conjur can be mapped and if we want to prevent it
- [ ] (Parent of #??) Dev - JWT sanitation/validation
- [ ] (Parent of #??) Dev - not to keep ID Token sensitive data in memory 

## Debts from Okta integration
- [ ] (Parent of #??) Research - self sign issue (more details: ONYX-1779) EE 2
- [ ] (Parent of #??) Dev - Base on self sign research decision EE 5
- [ ] (Parent of #??) Dev - Refactoring strategy EE 3
- [ ] (Parent of #??) Dev - Change previous OKTA APIs and adapt scripts and automations env EE 3
- [ ] (Parent of #??) Testing - UT Infrastructure rspec EE 2
 
## Testing
- [ ] (Parent of #??) Write test plan EE 2
- [ ] (Parent of #??) Automation infrastructure cucumber EE 3
- [ ] (Parent of #??) Open Source - Manually left overs EE ???
- [ ] (Parent of #??) Production env tests EE 5
    * Set Conjur Enterprise env with one satellite and one master
    * LDAP sync env
    * OIDC machine
    * configure ssl
    * run tests
- [ ] (Parent of #??) Dev UT EE ???
- [ ] (Parent of #??) Dev automation tests EE ???
- [ ] (Parent of #??) Fix Jenkins issues EE 2
 
## Implementation
- [ ] (Parent of #??) Dev end to end flow with hardcoded email as Conjur user in root policy EE 2
- [ ] (Parent of #??) Dev logic according to design EE 4
- [ ] (Parent of #??) Logs and error handeling EE 2
- [ ] (Parent of #??) Fixes/Surprises form previous Okta feature (Like the error in audit before identifying the User) EE 3
 
## Docs
- [ ] (Parent of #??) Write docs EE 3

**Comment by nessiLahav** [comment]
> * We have POCed and saw that also Conjur can validate an ID token even if it connect to the OIDC provider with its own client and not the JIRA one. If this is indeed possible that would be great!! if not the values of the client vars would be of JIRA.
> * Regarding the validating of the ID Token @nessiLahav has performed some POCs. Can you please elaborate on the differences you saw?
> * @nessiLahav \ shahar what do you think of locally validating?
> 
> Regarding the assumption of root. We had a long discussion where we realised that LDAP users is our main case. LDAP users currently in Conjur are defined in root. So for Beta purposes we will take only users that are defined in root. We will expand this later on as we go along.

**Comment by nessiLahav** [comment]
> > * We have POCed and saw that also Conjur can validate an ID token even if it connect to the OIDC provider with its own client and not the JIRA one. If this is indeed possible that would be great!! if not the values of the client vars would be of JIRA.
> > * Regarding the validating of the ID Token @nessiLahav has performed some POCs. Can you please elaborate on the differences you saw?
> > * @nessiLahav \ shahar what do you think of locally validating?
> > 
> > Regarding the assumption of root. We had a long discussion where we realised that LDAP users is our main case. LDAP users currently in Conjur are defined in root. So for Beta purposes we will take only users that are defined in root. We will expand this later on as we go along.

@InbalZilberman 

- About validating the ID Token i used in my POC with a simple introspect API of OpenID connect, i didn't examine a way to perform the validation locally, i will read about this
