### ISSUE TITLE
Authn-OIDC GA

### ISSUE THREAD

**Issue by InbalZilberman** [cyberark/conjur#974]
This Epic is related to #838 and is actually extending it.
Making sure OIDC authn is *GA ready* by:
1.  Enterprise Ready -  Make sure we have automated tests for all Enterprise scenario including:
1.1 Okta with LDAP Sync. 
1.2 Conjur HA  
2 Performance & Scalability
2.1 Design aspects of Scalability & Performance
2.2 Performance SLA - come up with an avg.  response time for regular call to authenticate. 
3, Supportability 
3.1 Error handling and supportability scenarios should be addressed & automated
3.2 Better error codes and logs level
4. Troubleshooting section in our documentation should be filled
5. Documentation 
5.1 Online and improved 
6. SDKs
6.1 Provide the ability to run the oidc Authn in Java and Python SDKs. More info will be provided later on

### **Overview**
Conjur OpenID Connect (OIDC) Authentication enables an application to use the OIDC
identity of a logged in user to authenticate with Conjur.
After OIDC authentication, the application can retrieve the secrets it needs for connecting
to services, such as a database, leveraging the ID Token acquired by the user from the
OIDC authentication.
How does it work?
![image](https://user-images.githubusercontent.com/26732770/56460791-230e1f00-63b1-11e9-9289-562eb67716ae.png)
1. A user logs into an application.
2. The application authenticates the user with an OIDC Provider.
3. The OIDC Provider sends back an ID Token.
4. The application sends out the ID Token to other application components or
microservices.
5. When an application component needs to retrieve a secret from Conjur, it
authenticates with Conjur using the ID Token it received from the OIDC Provider.
6. Conjur sends a Conjur access token to the application component.
7. The application component uses the Conjur access token to retrieve Conjur secrets
and perform other actions in Conjur.

### **Configure OIDC authentication**
This section describes how to set up the OIDC Authenticator.
1. Prerequisite: Define Conjur resources (users and variables), and grant
necessary permissions
The main purpose of the OIDC Authenticator is to grant Conjur access tokens to
application components authenticating with an ID Token of a user. Before configuring
OIDC authentication ensure that the necessary users and variables exist, and that
the users have been given permissions to use those variables.
Variables can be created and permitted to users using a Conjur policy.
Users can be created using a Conjur policy or can be imported using LDAP Sync.
For details, see [LDAP Sync](https://docs.conjur.org/Latest/en/Content/Integrations/ldap/ldap_sync.html#LDAPSync).
In the following example, the policy defines an application with a variable, requiredvar,
and a group of users, users, that are permitted to use that variable. It also
creates a user, alice, and adds it to the users group.
```
- !policy
id: the-application
body:
- !user alice
- !group users
- !grant
role: !group users
members:
- !user alice
- !variable required-var
- !permit
role: !group users
privilege: [ read, execute ]
resource: !variable required-var
```
2. Define the OIDC Authenticator
The OIDC Authenticator uses Conjur policy to define the authenticator configuration
settings and access permissions.
All OIDC Authenticator configurations begin with the policy identifier prefix
**conjur/authn-oidc**.
To identify the service, append a service ID to the authenticator type throughout the
configuration. Use the same service ID consistently in the configuration. For
example, for an ADFS OIDC Provider, the service ID can be adfs.
Create the required policy defining the OIDC Authenticator.
a. Copy the following policy into a text file, using the service ID that you have
chosen:
```
- !policy
id: conjur/authn-oidc/<service-id>
body:
- !webservice
annotations:
description: Authentication service for
<service-id>, based on OpenID Connect.
- !variable
id: provider-uri
- !variable
id: id-token-user-property
- !group users
annotations:
description: Group of users who can
authenticate using the authn-oidc/<service-id>
authenticator
- !permit
role: !group users
privilege: [ read, authenticate ]
resource: !webservice
```
b. Save the file as a .yml file. Use the following file naming convention: authn-oidc-
<service-id>.yml
c. Load the policy file under the root policy:
`conjur policy load root authn-oidc-<service-id>.yml`
3. Set values for the variables in the policy.
In the policy loaded above, the OIDC Authenticator uses variables that define its
configuration.
Use the following commands to set values for these variables:
```
conjur variable values add conjur/authn-oidc/<serviceid>/
provider-uri <Provider URI value>
conjur variable values add conjur/authn-oidc/<serviceid>/
id-token-user-property <ID Token user property
value>
```
4. Enable Conjur users to authenticate using the OIDC Authenticator
Create and load the following policy to enable Conjur users and hosts to authenticate
using OIDC:
```
- !grant
role: !group conjur/authn-oidc/<service-id>/users
member: !group the-application/users
```
5. Enable the OIDC Authenticator
Set the CONJUR_AUTHENTICATORS variable as an environment variable to enable the OIDC Authenticator.
`export CONJUR_AUTHENTICATORS=<authenticator-names>`
### **OIDC authentication flow**
The following flow represents how an application authenticates with Conjur using the
OIDC Authenticator. This flow assumes that the application already has an ID Token.

1. The application sends an authentication request to Conjur using the provided
Base64-encoded ID Token. The REST API of the OIDC Authenticator is described in detailed in the next section.
2. After receiving the ID Token authentication request, Conjur does the following:
a. Validates the ID Token against the OIDC Provider.
b. Extracts the Conjur username from the ID Token, using the value in the id-tokenuser-
property and looks for a user or host with that username.
c. Validates that the user with the above username exists in the root policy and has
permission to authenticate using the OIDC Authenticator.
d. Audits the authentication request.
e. Returns a Conjur access token to the application.
3. The application can retrieve the permitted secrets it needs using the Conjur access
token.
### **OIDC Authentication REST API**
Once the OIDC Authenticator is configured, you can send an authentication request as follows:
```
POST http://<conjur-appliance-hostname>/authnoidc/<
service-id>/<account>/authenticate
Header Content-Type: application/x-www-form-urlencoded
Body The body must include the ID Token that identifies the user.
```
URI Parameters
**service-id** The ID of the OIDC Provider, for example Okta
**account** The organization account name

Result
Returns a JSON object which contains a Conjur Access token of the user whose ID
Token is provided in the input.

h2. DOD
- [x] Implement an OpenIdConnect authn GA
- [x] Test plan written and reviewed by PO & QAA
- [x] Automatic integration tests written according to a test plan and passed successfully
- [x] UT written for all classes\functions\major logic flows and passed successfully
- [x] Security review was done
- [x] Security action items were taken
- [x] Supportability tasks were written 
 - [x] Enhance logs and supportability according to [https://ca-il-confluence.il.cyber-ark.com/display/rndp/Okta+Integration+With+Conjur+-+CLI#OktaIntegrationWithConjur-CLI-LogsGuidelines]
- [x] Fill in the logs and place here a link to the logs files
    - Logs: https://github.com/cyberark/conjur/blob/master/app/domain/logs.rb
    - Errors: https://github.com/cyberark/conjur/blob/master/app/domain/errors.rb
- [x] Logs were reviewed by TW and PO
- [x] Fill in the configurations in this epic
- [x] Configurations were reviewed by PO
- [x] Documentation HO to TW and review docs
